#!/bin/sh

echo "{$(/home/pi/czujnik/skrypt.py 2302 4 | sed -r 's/=/:"/g'| sed 's/*/"/g ; s/%/"/g' | awk -F' ' '{print $1",\n"$2}'),"  && echo "Date : '$(date +%d.%m.%Y)'," && echo "Time : '$(date +%H:%M:%S)'}"
